# Generated by Django 4.2.2 on 2023-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
