# Generated by Django 4.2.2 on 2023-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
