# Generated by Django 4.2.2 on 2023-08-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_image_image_alter_product_og_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='og_img',
        ),
    ]
