# Generated by Django 4.2.2 on 2023-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_delivery_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
