# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_delivery_done_remove_delivery_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
