# Generated by Django 4.2.2 on 2023-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_delivery_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WFP', 'WAITING_FOR_PAYMENT'), ('DP', 'DONE_PAYMENT'), ('DS', 'DONE_SEND'), ('C', 'CANCLED')], max_length=99),
        ),
    ]
