# Generated by Django 4.2.2 on 2023-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer_email',
        ),
    ]
