# Generated by Django 4.2.2 on 2023-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_orderer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'WAITING_FOR_PAYMENT'), ('WAITING_FOR_DEPOSIT', 'WAITING_FOR_DEPOSIT'), ('DONE_PAYMENT', 'DONE_PAYMENT'), ('DONE_SEND', 'DONE_SEND'), ('CANCELED', 'CANCELED')], max_length=99),
        ),
    ]
