# Generated by Django 4.2.2 on 2023-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
