# Generated by Django 4.2.2 on 2023-08-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
