# Generated by Django 4.2.2 on 2023-06-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_product_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer_name', models.CharField(max_length=99)),
                ('orderer_number', models.CharField(max_length=99)),
                ('orderer_email', models.EmailField(max_length=99)),
                ('recipient_name', models.CharField(max_length=99)),
                ('recipient_number', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('detail_address', models.CharField(max_length=99)),
                ('request', models.CharField(blank=True, max_length=99, null=True)),
                ('status', models.CharField(max_length=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
        ),
    ]
