# Generated by Django 4.2.2 on 2023-06-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item_rename_delivery_number_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
