# Generated by Django 4.2.2 on 2023-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='total_price',
        ),
    ]
