# Generated by Django 4.2.2 on 2023-06-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_price_item_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_price',
            new_name='price',
        ),
    ]
