# Generated by Django 4.2.2 on 2023-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='naver_name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
