# Generated by Django 4.2.2 on 2023-07-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_amount_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
