# Generated by Django 4.2.2 on 2023-07-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
