# Generated by Django 4.2.2 on 2023-10-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
        ('payment', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order'),
        ),
        migrations.CreateModel(
            name='RefundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankCode', models.CharField(max_length=2)),
                ('accountNumber', models.CharField(max_length=20)),
                ('holderName', models.CharField(max_length=60)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_account', to='payment.payment')),
            ],
        ),
    ]
